name: Build

on:
    pull_request:
        branches: '*'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn install

            - name: Check linter
              run: yarn lint:ci

            - name: Check linter
              run: yarn test

            - name: Check linter
              run: yarn build
